sudo: required
dist: trusty
language: generic
script: ./.docker-build/build-package-in-docker.sh -e "BUILD_TAG=$TRAVIS_TAG" -e "RUMPRUN_PUBLISH_CONFIG=hw_generic" -e npm_config_unsafe_perm=true davedoesdev/rumprun-pkgbuild-x86_64-rumprun-netbsd-hw

services:
  - docker

env:
  - PACKAGE=erlang
  - PACKAGE=haproxy
  - PACKAGE=hiawatha
  - PACKAGE=leveldb
  - PACKAGE=libcurl
  - PACKAGE=libevent
  - PACKAGE=libxml2
  - PACKAGE=mathopd
  - PACKAGE=memcached
  - PACKAGE=mpg123
  - PACKAGE=mysql
  - PACKAGE=nanomsg
  - PACKAGE=nginx
  - PACKAGE=ngircd
  - PACKAGE=nodejs SWAP_GB=4
# broken: issue #92
#  - PACKAGE=openmp
  - PACKAGE=pcre
  - PACKAGE=php5
  - PACKAGE=php7
  - PACKAGE=python3
  - PACKAGE=redis
# Disabled, does not actually build anything interesting
#  - PACKAGE=roundcube
  - PACKAGE=ruby
# Disabled, build takes several hours
#  - PACKAGE=rust
  - PACKAGE=sqlite

#notifications:
#  irc:
#    channels:
#      - "chat.freenode.net#rumpkernel-builds"
#    template:
#      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
#    skip_join: true
#    use_notice: true
#  email:
#    recipients:
#      - rumpkernel-builds@freelists.org
#    on_success: always
#    on_failure: always

before_deploy: ./.publish/commit.sh

deploy:
  provider: releases
  api_key:
    secure: gA4x3pyspSnbPRFSYyLcPOEH8gp70/kfgue6065k0zLwzfUPusuouVB5o4UXVWe601OXOeEEejmln7oTzSJME8tqwHXWpbIsAlo4qvNtQnccq6l+SXmwJH0n92EUiu2n9EMds7bhlK+Pogv9e41YvkrkBlyt/JWLppM9YPxOIs/jYw3C58Bu3slBfspq0uoYswr8tj4zv20P5r6Z70ApmOsavuHXPLEsdMl4/XTYX4+aLUL//seGQ1Ul43TncVk17QvhR/jGxCpDIj1BRnKTyAu9wE4RHUJ4rdF5hHy7JlazqWjArD8i7dz3A4rgIojoEYSjaJ+e/fgnSzx0TUgvnR6kHJW047qbt59hfHMj57kxrrin+mYsZqG03Bf991ldt0v9D9gLnfxzTvVRJ8CSVz/vzgksWNNucyfDKS1gchrmn5oboq52tFsNZR5OGDySDJMcVlWYvOnzb9mn2PJyrwflA47iII9k+0vReE6lVXuXMq4mC6t/Nff8U2s8t3Sm/IoFb3Jej9Pf2k0AWPirNShd9qYmHnJ3Ps/abNAXEjeOvoGXJhc0FRT8HgGwaQv+Mg0EwmBW9/qf3iLN6jXr7AsmGVbGZAO+0jNeYiproEoPue7WNWPYRFbC6nBUHNe2Ic26Ek78t9WVggOqeedLhTlU2tjrdkMXfGrBM4EiYqc=
  file_glob: true
  file: ./.publish/*.tar.xz
  skip_cleanup: true
  on:
    repo: davedoesdev/rumprun-packages
    tags: true
    all_branches: true

after_deploy:
  - python .docker-build/travis_after_all.py
  - |
      if [ -f .to_export_back ]; then
        export $(cat .to_export_back)
        if [ "$BUILD_LEADER" = "YES" ]; then
          if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
            echo "All jobs succeeded! PUBLISHING..."
          else
            echo "Some jobs failed"
          fi
        fi
      fi
